In [11]:
import os
import PyPDF2
import numpy as np
import pandas as pd
from tabula.io import read_pdf
from datetime import datetime
import re

In [12]:
file_name = r"C:\Users\admin\Downloads\26.04.2024 £2731.87 Chemical Corporation.pdf"
r"C:\Users\admin\Downloads\26.04.2024 £2731.87 Chemical Corporation.pdf"

'C:\\Users\\admin\\Downloads\\26.04.2024 £2731.87 Chemical Corporation.pdf'

In [13]:
invoice_type = "Products"
# inputFolder = os.path.abspath('..\\Forge')

input_file = fr"C:\Users\admin\Downloads\26.04.2024 £2731.87 Chemical Corporation.pdf"

In [14]:
table1 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(35,362,258,564),
                  columns=[451,564],
                  pandas_options={'header': None},
                  encoding="windows-1254")

heading = table1[0]
heading = heading.dropna(subset=[1])  # Remove rows with NaN in column 1
display(heading)

name = "Chemical Corporation"
row_docnum = heading.index[heading[0] == "Invoice Number"].tolist()[0]
docnum = heading[1][row_docnum]
print(docnum)

row_date = heading.index[heading[0] == "Invoice Date"].tolist()[0]
date = heading[1][row_date]
date = str(datetime.strptime(date, "%d/%m/%Y"))
print(date)

row_ordernum = heading.index[heading[0] == "Your Reference"].tolist()[0]
ordernum = heading[1][row_ordernum]
print(ordernum)

transfernum = None
print(transfernum)

                       0           1
0         Invoice Number  0000333200
1           Invoice Date  26/04/2024
2        Sales Order No.  0000301400
3         Your Reference     PO36283
4           Account Ref.         MLP
7  Unit 5B, Lyne Mushroo      m Farm

0000333200
2024-04-26 00:00:00
PO36283
None

In [15]:
table2 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(285,42,730,562),
                  columns=[121,331,357,400,440,505,560],
                  pandas_options={'header': None},
                  encoding="windows-1254")
content=table2[0]

content

,0,1,2,3,4,5,6
0,NaN,despatch when at full pallet,NaN,NaN,NaN,0.00,NaN
1,XOM-153669,Mobil 1 FS 0w40 5lt 153669,12.0,5lt,1.0,32.75,393.00
2,XOM-156578,Mobil ATF 3309 12X1L EU-SWW*-EU156578,1.0,12x1lt,1.0,73.20,73.20
3,XOM-153685,Mobil 1 ESP X2 0w20 5lt 153685,8.0,5lt,1.0,35.95,287.60
4,XOM-143990,Mobilux EP 004 18kg 143990,3.0,18kg,1.0,88.92,266.76
5,XOM-154488,Mobil Super 3000 Formula F 0w30 5lt 154488,4.0,5lt,1.0,24.50,98.00
6,XOM-151451,Mobil Super 3000 XE 5w30 5lt * 151451,4.0,5lt,1.0,23.95,95.80
7,XOM-157307,M-SUP1000 X1 15W40 4X5L ML 157307,1.0,4x5lt,1.0,69.60,69.60
8,XOM-153746,Mobil Super 3000 Formula VC 0w20 5lt 153746,4.0,5lt,1.0,28.15,112.60
9,XOM-124231,Mobilfluid 424 20lt 124231,2.0,20lt,1.0,60.40,120.80
10,XOM-149635,Mobilgear 600 XP 100 20lt 149635,1.0,20lt,1.0,61.60,61.60
11,XOM-153309,Mobilube PTX 75w90 20lt 153309,1.0,20lt,1.0,156.20,156.20
12,XOM-152360,Mobil SHC Cibus 100 20lt 152360,1.0,20lt,1.0,171.80,171.80
13,XOM-155520,Mobil 1 ESP X3 0w40 Bag-In-Box 20lt 155520,1.0,20lt,1.0,136.20,136.20
14,XOM-111461,Mobil Nuto H 68 20lt 111461,1.0,20lt,1.0,38.40,38.40
15,XOM-127782,Mobil Pyrolube 830 20lt 127782,1.0,20lt,1.0,195.00,195.00
16,NaN,Code 155693 obsolete emailed customer 25/4,NaN,NaN,NaN,0.00,NaN
17,NaN,with replacement 157467,NaN,NaN,NaN,NaN,NaN

In [16]:

content = content[content[0].notnull()].iloc[:, 0:].reset_index(drop=True)  # Remove NaN
content = content.dropna(subset=[2]).reset_index(drop=True)  # Remove rows with NaN in column 2

content

,0,1,2,3,4,5,6
0,XOM-153669,Mobil 1 FS 0w40 5lt 153669,12.0,5lt,1.0,32.75,393.00
1,XOM-156578,Mobil ATF 3309 12X1L EU-SWW*-EU156578,1.0,12x1lt,1.0,73.20,73.20
2,XOM-153685,Mobil 1 ESP X2 0w20 5lt 153685,8.0,5lt,1.0,35.95,287.60
3,XOM-143990,Mobilux EP 004 18kg 143990,3.0,18kg,1.0,88.92,266.76
4,XOM-154488,Mobil Super 3000 Formula F 0w30 5lt 154488,4.0,5lt,1.0,24.50,98.00
5,XOM-151451,Mobil Super 3000 XE 5w30 5lt * 151451,4.0,5lt,1.0,23.95,95.80
6,XOM-157307,M-SUP1000 X1 15W40 4X5L ML 157307,1.0,4x5lt,1.0,69.60,69.60
7,XOM-153746,Mobil Super 3000 Formula VC 0w20 5lt 153746,4.0,5lt,1.0,28.15,112.60
8,XOM-124231,Mobilfluid 424 20lt 124231,2.0,20lt,1.0,60.40,120.80
9,XOM-149635,Mobilgear 600 XP 100 20lt 149635,1.0,20lt,1.0,61.60,61.60
10,XOM-153309,Mobilube PTX 75w90 20lt 153309,1.0,20lt,1.0,156.20,156.20
11,XOM-152360,Mobil SHC Cibus 100 20lt 152360,1.0,20lt,1.0,171.80,171.80
12,XOM-155520,Mobil 1 ESP X3 0w40 Bag-In-Box 20lt 155520,1.0,20lt,1.0,136.20,136.20
13,XOM-111461,Mobil Nuto H 68 20lt 111461,1.0,20lt,1.0,38.40,38.40
14,XOM-127782,Mobil Pyrolube 830 20lt 127782,1.0,20lt,1.0,195.00,195.00

In [17]:
content.rename(columns={
    0: 'Item Code',
    1: 'Description',
    2: 'Quantity',
    3: 'Unit',
    4: 'VAT Code',
    5: 'Unit Price',
    6: 'Net'}, inplace=True)

display(content)

,Item Code,Description,Quantity,Unit,VAT Code,Unit Price,Net
0,XOM-153669,Mobil 1 FS 0w40 5lt 153669,12.0,5lt,1.0,32.75,393.00
1,XOM-156578,Mobil ATF 3309 12X1L EU-SWW*-EU156578,1.0,12x1lt,1.0,73.20,73.20
2,XOM-153685,Mobil 1 ESP X2 0w20 5lt 153685,8.0,5lt,1.0,35.95,287.60
3,XOM-143990,Mobilux EP 004 18kg 143990,3.0,18kg,1.0,88.92,266.76
4,XOM-154488,Mobil Super 3000 Formula F 0w30 5lt 154488,4.0,5lt,1.0,24.50,98.00
5,XOM-151451,Mobil Super 3000 XE 5w30 5lt * 151451,4.0,5lt,1.0,23.95,95.80
6,XOM-157307,M-SUP1000 X1 15W40 4X5L ML 157307,1.0,4x5lt,1.0,69.60,69.60
7,XOM-153746,Mobil Super 3000 Formula VC 0w20 5lt 153746,4.0,5lt,1.0,28.15,112.60
8,XOM-124231,Mobilfluid 424 20lt 124231,2.0,20lt,1.0,60.40,120.80
9,XOM-149635,Mobilgear 600 XP 100 20lt 149635,1.0,20lt,1.0,61.60,61.60
10,XOM-153309,Mobilube PTX 75w90 20lt 153309,1.0,20lt,1.0,156.20,156.20
11,XOM-152360,Mobil SHC Cibus 100 20lt 152360,1.0,20lt,1.0,171.80,171.80
12,XOM-155520,Mobil 1 ESP X3 0w40 Bag-In-Box 20lt 155520,1.0,20lt,1.0,136.20,136.20
13,XOM-111461,Mobil Nuto H 68 20lt 111461,1.0,20lt,1.0,38.40,38.40
14,XOM-127782,Mobil Pyrolube 830 20lt 127782,1.0,20lt,1.0,195.00,195.00

In [18]:
dict_content = content.to_dict(orient='records')
dict_content


line_items=[]
for item in dict_content:
    # print(item)
    
    partNum = item['Item Code']
    desc = item['Description']
    quantity = item['Quantity']
    netTotal = item['Net']

    print(partNum)
    
    line_item = {"line_type": "inventory",
                        "sku": partNum,
                        "name": desc,
                        "quantity": int(quantity),
                        "net_total": float(netTotal),
                        "tax_type": "INPUT2"}
    
    line_items.append(line_item)
    
print(line_items)

XOM-153669
XOM-156578
XOM-153685
XOM-143990
XOM-154488
XOM-151451
XOM-157307
XOM-153746
XOM-124231
XOM-149635
XOM-153309
XOM-152360
XOM-155520
XOM-111461
XOM-127782
[{'line_type': 'inventory', 'sku': 'XOM-153669', 'name': 'Mobil 1 FS 0w40 5lt 153669', 'quantity': 12, 'net_total': 393.0, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-156578', 'name': 'Mobil ATF 3309 12X1L EU-SWW*-EU156578', 'quantity': 1, 'net_total': 73.2, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-153685', 'name': 'Mobil 1 ESP X2 0w20 5lt 153685', 'quantity': 8, 'net_total': 287.6, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-143990', 'name': 'Mobilux EP 004 18kg 143990', 'quantity': 3, 'net_total': 266.76, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-154488', 'name': 'Mobil Super 3000 Formula F 0w30 5lt 154488', 'quantity': 4, 'net_total': 98.0, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-151451', 'name': 'Mobil Super 3000 XE 5w30 5lt * 151451', 'quantity': 4, 'net_total': 95.8, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-157307', 'name': 'M-SUP1000 X1 15W40 4X5L ML 157307', 'quantity': 1, 'net_total': 69.6, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-153746', 'name': 'Mobil Super 3000 Formula VC 0w20 5lt 153746', 'quantity': 4, 'net_total': 112.6, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-124231', 'name': 'Mobilfluid 424 20lt 124231', 'quantity': 2, 'net_total': 120.8, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-149635', 'name': 'Mobilgear 600 XP 100 20lt 149635', 'quantity': 1, 'net_total': 61.6, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-153309', 'name': 'Mobilube PTX 75w90 20lt 153309', 'quantity': 1, 'net_total': 156.2, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-152360', 'name': 'Mobil SHC Cibus 100 20lt 152360', 'quantity': 1, 'net_total': 171.8, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-155520', 'name': 'Mobil 1 ESP X3 0w40 Bag-In-Box 20lt 155520', 'quantity': 1, 'net_total': 136.2, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-111461', 'name': 'Mobil Nuto H 68 20lt 111461', 'quantity': 1, 'net_total': 38.4, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'XOM-127782', 'name': 'Mobil Pyrolube 830 20lt 127782', 'quantity': 1, 'net_total': 195.0, 'tax_type': 'INPUT2'}]

In [19]:
table3 = read_pdf(input_file,
            pages=1,
            silent=True,
            guess=False,
            area=(733,363,807,562),
            columns=[450,562],
            pandas_options={'header': None},
            encoding='windows-1254')

total_content=table3[0]

#total_content = total_content.dropna(subset=[0,1])  # Remove rows with NaN in column 0 & 1
#total_content = total_content.dropna(subset=[0]).reset_index(drop=True)
display(total_content)

row_index = total_content.index[total_content[0] == "GROSS"].tolist()[0]


final_total = float(total_content[1][row_index])
display(final_total)

       0        1
0    NET  2276.56
1    VAT   455.31
2  GROSS  2731.87

2731.87

In [20]:
payload = {}
keys = ["Source File",
        "Type",
        "Name",
        "Date",
        "Reference No.",
        "Order No.",
        "Transfer No.",
        "Document No.",
        "Line Items",
        "Total"]

values = [file_name,
        invoice_type,
        name,
        date,
        docnum,
        ordernum,
        transfernum,
        None,
        line_items,
        final_total]

for i, key in enumerate(keys):
    payload[key] = values[i]

payload

{'Source File': 'C:\\Users\\admin\\Downloads\\26.04.2024 £2731.87 Chemical Corporation.pdf',
 'Type': 'Products',
 'Name': 'Chemical Corporation',
 'Date': '2024-04-26 00:00:00',
 'Reference No.': '0000333200',
 'Order No.': 'PO36283',
 'Transfer No.': None,
 'Document No.': None,
 'Line Items': [{'line_type': 'inventory',
   'sku': 'XOM-153669',
   'name': 'Mobil 1 FS 0w40 5lt 153669',
   'quantity': 12,
   'net_total': 393.0,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-156578',
   'name': 'Mobil ATF 3309 12X1L EU-SWW*-EU156578',
   'quantity': 1,
   'net_total': 73.2,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-153685',
   'name': 'Mobil 1 ESP X2 0w20 5lt 153685',
   'quantity': 8,
   'net_total': 287.6,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-143990',
   'name': 'Mobilux EP 004 18kg 143990',
   'quantity': 3,
   'net_total': 266.76,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-154488',
   'name': 'Mobil Super 3000 Formula F 0w30 5lt 154488',
   'quantity': 4,
   'net_total': 98.0,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-151451',
   'name': 'Mobil Super 3000 XE 5w30 5lt * 151451',
   'quantity': 4,
   'net_total': 95.8,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-157307',
   'name': 'M-SUP1000 X1 15W40 4X5L ML 157307',
   'quantity': 1,
   'net_total': 69.6,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-153746',
   'name': 'Mobil Super 3000 Formula VC 0w20 5lt 153746',
   'quantity': 4,
   'net_total': 112.6,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-124231',
   'name': 'Mobilfluid 424 20lt 124231',
   'quantity': 2,
   'net_total': 120.8,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-149635',
   'name': 'Mobilgear 600 XP 100 20lt 149635',
   'quantity': 1,
   'net_total': 61.6,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-153309',
   'name': 'Mobilube PTX 75w90 20lt 153309',
   'quantity': 1,
   'net_total': 156.2,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-152360',
   'name': 'Mobil SHC Cibus 100 20lt 152360',
   'quantity': 1,
   'net_total': 171.8,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-155520',
   'name': 'Mobil 1 ESP X3 0w40 Bag-In-Box 20lt 155520',
   'quantity': 1,
   'net_total': 136.2,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-111461',
   'name': 'Mobil Nuto H 68 20lt 111461',
   'quantity': 1,
   'net_total': 38.4,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'XOM-127782',
   'name': 'Mobil Pyrolube 830 20lt 127782',
   'quantity': 1,
   'net_total': 195.0,
   'tax_type': 'INPUT2'}],
 'Total': 2731.87}