In [220]:
import os
import PyPDF2
import numpy as np
import pandas as pd
from tabula.io import read_pdf
from datetime import datetime
import re

In [221]:
file_name = r"C:\Users\admin\Downloads\20.11.2023 £1,796.40 On-Line Auto Sport.pdf"

r"C:\Users\admin\Downloads\20.02.2023 £3,285.15 On-Line Auto Sport Limited.pdf"

'C:\\Users\\admin\\Downloads\\20.02.2023 £3,285.15 On-Line Auto Sport Limited.pdf'

In [222]:
invoice_type = "Products"

input_file = fr"C:\Users\admin\Downloads\11.03.2024 £4,382.98 On-Line Auto Sport.pdf"

In [223]:
name = "On-Line Auto Sport"

table1 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(160,310,280,580),
                  columns=[580],
                  pandas_options={'header': None},
                  encoding="windows-1254")

heading = table1[0]
display(heading)

docnum = heading[0][0].split(' ',1)[1].replace(' ','')
print(docnum)

date = heading[0][1].split(':')[1].replace(' ','')
date = str(datetime.strptime(date, "%d/%m/%Y"))
print(date)

ordernum = heading[0][2].split(':')[1].replace(' ','')

transfernum = None
print(ordernum)
print(transfernum)

                                 0
0                 Invoice   212510
1                Date : 11/03/2024
2  Your Order No. :PO33922/PO34413
3            Account Ref. : MLPE01

212510
2024-03-11 00:00:00
PO33922/PO34413
None

In [224]:
with open(input_file,'rb') as pdf_file:
    pdf_reader = PyPDF2.PdfReader(pdf_file)
    num_pages = len(pdf_reader.pages)

print(num_pages)

2

In [225]:
#create loop to go through the pages
all_content = []
for page in range(1, num_pages + 1):
    table2 = read_pdf(input_file,
                    pages=page,
                    silent=True,
                    guess=False,
                    area=(277,24,720,577),
                    columns=[83.5,154,438,502,577],
                    pandas_options={'header': None},
                    encoding="windows-1254")
    contenti = table2[0]
    all_content.append(contenti)

content = pd.concat(all_content).reset_index(drop=True)
display(content)

,0,1,2,3,4
0,Quantity,Part Number,Product Description,Each To,tal Amount
1,NaN,M,** ORDER No. PO33922 **,NaN,NaN
2,1.00,R00049084,BMW Z3 FRONT LIP SPOILER,£91.21,£91.21
3,1.00,R00088028,VW GOLF MK7 REAR DIFFUSER GLASS BLACK,£134.77,£134.77
4,1.00,R00025025,MB W202 C CLASS 93-97 REAR LOWER APRON,£96.66,£96.66
5,1.00,R00025070,MERCEDES W202 RIEGER FRONT BUMPER,£223.94,£223.94
6,1.00,R00053467,BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340,£134.77,£134.77
7,1.00,R00051002,ASTRA F RADIATOR GRILLE,£53.77,£53.77
8,1.00,R00055103,AUDI TT 8N SIDE SKIRT LEFT,£67.39,£67.39
9,1.00,R00055104,AUDI TT 8N SIDE SKIRT RIGHT,£67.39,£67.39
10,1.00,R00025020,MB W202 C CLASS RERA WINDOW SPOILER,£46.97,£46.97
11,NaN,M,** ORDER No. PO34413 **,NaN,NaN
12,1.00,R00025045,MB W201 190 SIDE SKIRT LEFT,£46.97,£46.97
13,1.00,R00025046,MB W201 190 SIDE SKIRT RIGHT,£46.97,£46.97
14,1.00,R00025073,MB W202 C CLASS SIDE SKIRT LEFT,£66.71,£66.71
15,1.00,R00025074,MW W202 C CLASS SIDE SKIRT RIGHT,£66.71,£66.71
16,1.00,R00048221,VW LUPO/SEAT AROSA SIDE SKIRT RIGHT,£43.56,£43.56
17,1.00,R00055072,AUDI A4 B5 RS4 LOOK FRONT BUMPER,£202.84,£202.84
18,1.00,R00055113,AUDI TT 8N VENTED SIDE SKIRT LEFT,£91.21,£91.21
19,1.00,R00055114,AUDI TT 8N VENTED SIDE SKIRT RIGHT,£91.21,£91.21
20,1.00,R00055488,AUDI A5/S5 SIDE SKIRT SPLITTER LEFT,£57.18,£57.18
21,1.00,R00055489,AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT,£57.18,£57.18
22,1.00,R00057004,PORSCHE BOXSTER 986 SIDE SKIRT LEFT,£132.05,£132.05
23,1.00,R00057005,PORSCHE BOXSTER 986 SIDE SKIRT RIGHT,£132.05,£132.05
24,1.00,R00059012,VW GOLD MK4 FRONT GRILLE,£40.16,£40.16
25,1.00,R00059017,VW GOLF MK4 FRONT BUMPER,£202.84,£202.84
26,1.00,R00088247,AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER,£111.63,£111.63
27,1.00,R00099844,AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK,£134.77,£134.77
28,1.00,R00099858,BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU,£167.45,£167.45
29,Quantity,Part Number,Product Description,Each To,tal Amount
30,1.00,R00088172,AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC,£134.77,£134.77
31,1.00,R00059524,VW GOLF 6 GTi REAR DIFFUSER,£101.42,£101.42
32,1.00,R00059328,VW GOLF MK5 REAR LOWER APRON,£104.82,£104.82
33,1.00,R00034134,FOCUS MK2 3 DOOR SIDE SKIRT LEFT,£66.71,£66.71
34,1.00,R00034135,FOCUS MK2 3 DOOR SIDE SKIRT RIGHT,£66.71,£66.71
35,1.00,R00088095,SKODA RAPID NH REAR DIFFUSER GLOSS BLACK,£125.24,£125.24
36,1.00,R00047006,POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT,£36.76,£36.76
37,1.00,R00047007,POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT,£36.76,£36.76
38,1.00,R00034177,FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W,£257.29,£257.29
39,1.00,R00051119,ASTRA 4 VENTED SKIRT (5-DR) RH,£46.97,£46.97
40,1.00,R00027014,SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT,£66.71,£66.71
41,DE,LIVER TO,:,NaN,NaN
42,NaN,NaN,Net Amount,NaN,"£3,652.52"

In [226]:
content[0] = pd.to_numeric(content[0], errors='coerce')  # Remove anything that not number in column 0
content = content.dropna(subset=[0]).reset_index(drop=True) # Remove rows with NaN in column 0

content[[3,4]] = content[[3,4]].replace('[£,$, ]','', regex=True).astype('string')

content

,0,1,2,3,4
0,1.0,R00049084,BMW Z3 FRONT LIP SPOILER,91.21,91.21
1,1.0,R00088028,VW GOLF MK7 REAR DIFFUSER GLASS BLACK,134.77,134.77
2,1.0,R00025025,MB W202 C CLASS 93-97 REAR LOWER APRON,96.66,96.66
3,1.0,R00025070,MERCEDES W202 RIEGER FRONT BUMPER,223.94,223.94
4,1.0,R00053467,BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340,134.77,134.77
5,1.0,R00051002,ASTRA F RADIATOR GRILLE,53.77,53.77
6,1.0,R00055103,AUDI TT 8N SIDE SKIRT LEFT,67.39,67.39
7,1.0,R00055104,AUDI TT 8N SIDE SKIRT RIGHT,67.39,67.39
8,1.0,R00025020,MB W202 C CLASS RERA WINDOW SPOILER,46.97,46.97
9,1.0,R00025045,MB W201 190 SIDE SKIRT LEFT,46.97,46.97
10,1.0,R00025046,MB W201 190 SIDE SKIRT RIGHT,46.97,46.97
11,1.0,R00025073,MB W202 C CLASS SIDE SKIRT LEFT,66.71,66.71
12,1.0,R00025074,MW W202 C CLASS SIDE SKIRT RIGHT,66.71,66.71
13,1.0,R00048221,VW LUPO/SEAT AROSA SIDE SKIRT RIGHT,43.56,43.56
14,1.0,R00055072,AUDI A4 B5 RS4 LOOK FRONT BUMPER,202.84,202.84
15,1.0,R00055113,AUDI TT 8N VENTED SIDE SKIRT LEFT,91.21,91.21
16,1.0,R00055114,AUDI TT 8N VENTED SIDE SKIRT RIGHT,91.21,91.21
17,1.0,R00055488,AUDI A5/S5 SIDE SKIRT SPLITTER LEFT,57.18,57.18
18,1.0,R00055489,AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT,57.18,57.18
19,1.0,R00057004,PORSCHE BOXSTER 986 SIDE SKIRT LEFT,132.05,132.05
20,1.0,R00057005,PORSCHE BOXSTER 986 SIDE SKIRT RIGHT,132.05,132.05
21,1.0,R00059012,VW GOLD MK4 FRONT GRILLE,40.16,40.16
22,1.0,R00059017,VW GOLF MK4 FRONT BUMPER,202.84,202.84
23,1.0,R00088247,AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER,111.63,111.63
24,1.0,R00099844,AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK,134.77,134.77
25,1.0,R00099858,BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU,167.45,167.45
26,1.0,R00088172,AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC,134.77,134.77
27,1.0,R00059524,VW GOLF 6 GTi REAR DIFFUSER,101.42,101.42
28,1.0,R00059328,VW GOLF MK5 REAR LOWER APRON,104.82,104.82
29,1.0,R00034134,FOCUS MK2 3 DOOR SIDE SKIRT LEFT,66.71,66.71
30,1.0,R00034135,FOCUS MK2 3 DOOR SIDE SKIRT RIGHT,66.71,66.71
31,1.0,R00088095,SKODA RAPID NH REAR DIFFUSER GLOSS BLACK,125.24,125.24
32,1.0,R00047006,POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT,36.76,36.76
33,1.0,R00047007,POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT,36.76,36.76
34,1.0,R00034177,FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W,257.29,257.29
35,1.0,R00051119,ASTRA 4 VENTED SKIRT (5-DR) RH,46.97,46.97
36,1.0,R00027014,SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT,66.71,66.71

In [227]:
content.rename(columns={
    0: 'Quantity',
    1: 'Part Number',
    2: 'Product Description',
    3: 'Each',
    4: 'Total Amount'}, inplace=True)

display(content)

,Quantity,Part Number,Product Description,Each,Total Amount
0,1.0,R00049084,BMW Z3 FRONT LIP SPOILER,91.21,91.21
1,1.0,R00088028,VW GOLF MK7 REAR DIFFUSER GLASS BLACK,134.77,134.77
2,1.0,R00025025,MB W202 C CLASS 93-97 REAR LOWER APRON,96.66,96.66
3,1.0,R00025070,MERCEDES W202 RIEGER FRONT BUMPER,223.94,223.94
4,1.0,R00053467,BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340,134.77,134.77
5,1.0,R00051002,ASTRA F RADIATOR GRILLE,53.77,53.77
6,1.0,R00055103,AUDI TT 8N SIDE SKIRT LEFT,67.39,67.39
7,1.0,R00055104,AUDI TT 8N SIDE SKIRT RIGHT,67.39,67.39
8,1.0,R00025020,MB W202 C CLASS RERA WINDOW SPOILER,46.97,46.97
9,1.0,R00025045,MB W201 190 SIDE SKIRT LEFT,46.97,46.97
10,1.0,R00025046,MB W201 190 SIDE SKIRT RIGHT,46.97,46.97
11,1.0,R00025073,MB W202 C CLASS SIDE SKIRT LEFT,66.71,66.71
12,1.0,R00025074,MW W202 C CLASS SIDE SKIRT RIGHT,66.71,66.71
13,1.0,R00048221,VW LUPO/SEAT AROSA SIDE SKIRT RIGHT,43.56,43.56
14,1.0,R00055072,AUDI A4 B5 RS4 LOOK FRONT BUMPER,202.84,202.84
15,1.0,R00055113,AUDI TT 8N VENTED SIDE SKIRT LEFT,91.21,91.21
16,1.0,R00055114,AUDI TT 8N VENTED SIDE SKIRT RIGHT,91.21,91.21
17,1.0,R00055488,AUDI A5/S5 SIDE SKIRT SPLITTER LEFT,57.18,57.18
18,1.0,R00055489,AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT,57.18,57.18
19,1.0,R00057004,PORSCHE BOXSTER 986 SIDE SKIRT LEFT,132.05,132.05
20,1.0,R00057005,PORSCHE BOXSTER 986 SIDE SKIRT RIGHT,132.05,132.05
21,1.0,R00059012,VW GOLD MK4 FRONT GRILLE,40.16,40.16
22,1.0,R00059017,VW GOLF MK4 FRONT BUMPER,202.84,202.84
23,1.0,R00088247,AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER,111.63,111.63
24,1.0,R00099844,AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK,134.77,134.77
25,1.0,R00099858,BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU,167.45,167.45
26,1.0,R00088172,AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC,134.77,134.77
27,1.0,R00059524,VW GOLF 6 GTi REAR DIFFUSER,101.42,101.42
28,1.0,R00059328,VW GOLF MK5 REAR LOWER APRON,104.82,104.82
29,1.0,R00034134,FOCUS MK2 3 DOOR SIDE SKIRT LEFT,66.71,66.71
30,1.0,R00034135,FOCUS MK2 3 DOOR SIDE SKIRT RIGHT,66.71,66.71
31,1.0,R00088095,SKODA RAPID NH REAR DIFFUSER GLOSS BLACK,125.24,125.24
32,1.0,R00047006,POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT,36.76,36.76
33,1.0,R00047007,POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT,36.76,36.76
34,1.0,R00034177,FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W,257.29,257.29
35,1.0,R00051119,ASTRA 4 VENTED SKIRT (5-DR) RH,46.97,46.97
36,1.0,R00027014,SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT,66.71,66.71

In [228]:
dict_content = content.to_dict(orient='records')
dict_content

line_items=[]
for item in dict_content:

    partNum = item['Part Number']
    desc = item['Product Description']
    quantity = item['Quantity']
    netTotal = item['Total Amount']

    print(partNum)
    
    line_item = {"line_type": "inventory",
                        "sku": str(partNum),
                        "name": desc,
                        "quantity": int(quantity),
                        "net_total": float(netTotal),
                        "tax_type": "INPUT2"}
    
    line_items.append(line_item)
    
print(line_items)

R00049084
R00088028
R00025025
R00025070
R00053467
R00051002
R00055103
R00055104
R00025020
R00025045
R00025046
R00025073
R00025074
R00048221
R00055072
R00055113
R00055114
R00055488
R00055489
R00057004
R00057005
R00059012
R00059017
R00088247
R00099844
R00099858
R00088172
R00059524
R00059328
R00034134
R00034135
R00088095
R00047006
R00047007
R00034177
R00051119
R00027014
[{'line_type': 'inventory', 'sku': 'R00049084', 'name': 'BMW Z3 FRONT LIP SPOILER', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088028', 'name': 'VW GOLF MK7 REAR DIFFUSER GLASS BLACK', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025025', 'name': 'MB W202 C CLASS 93-97 REAR LOWER APRON', 'quantity': 1, 'net_total': 96.66, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025070', 'name': 'MERCEDES W202 RIEGER FRONT BUMPER', 'quantity': 1, 'net_total': 223.94, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00053467', 'name': 'BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00051002', 'name': 'ASTRA F RADIATOR GRILLE', 'quantity': 1, 'net_total': 53.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055103', 'name': 'AUDI TT 8N SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 67.39, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055104', 'name': 'AUDI TT 8N SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 67.39, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025020', 'name': 'MB W202 C CLASS RERA WINDOW SPOILER', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025045', 'name': 'MB W201 190 SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025046', 'name': 'MB W201 190 SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025073', 'name': 'MB W202 C CLASS SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025074', 'name': 'MW W202 C CLASS SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00048221', 'name': 'VW LUPO/SEAT AROSA SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 43.56, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055072', 'name': 'AUDI A4 B5 RS4 LOOK FRONT BUMPER', 'quantity': 1, 'net_total': 202.84, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055113', 'name': 'AUDI TT 8N VENTED SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055114', 'name': 'AUDI TT 8N VENTED SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055488', 'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER LEFT', 'quantity': 1, 'net_total': 57.18, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055489', 'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT', 'quantity': 1, 'net_total': 57.18, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00057004', 'name': 'PORSCHE BOXSTER 986 SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 132.05, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00057005', 'name': 'PORSCHE BOXSTER 986 SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 132.05, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059012', 'name': 'VW GOLD MK4 FRONT GRILLE', 'quantity': 1, 'net_total': 40.16, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059017', 'name': 'VW GOLF MK4 FRONT BUMPER', 'quantity': 1, 'net_total': 202.84, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088247', 'name': 'AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER', 'quantity': 1, 'net_total': 111.63, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00099844', 'name': 'AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00099858', 'name': 'BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU', 'quantity': 1, 'net_total': 167.45, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088172', 'name': 'AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059524', 'name': 'VW GOLF 6 GTi REAR DIFFUSER', 'quantity': 1, 'net_total': 101.42, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059328', 'name': 'VW GOLF MK5 REAR LOWER APRON', 'quantity': 1, 'net_total': 104.82, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034134', 'name': 'FOCUS MK2 3 DOOR SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034135', 'name': 'FOCUS MK2 3 DOOR SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088095', 'name': 'SKODA RAPID NH REAR DIFFUSER GLOSS BLACK', 'quantity': 1, 'net_total': 125.24, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00047006', 'name': 'POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT', 'quantity': 1, 'net_total': 36.76, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00047007', 'name': 'POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT', 'quantity': 1, 'net_total': 36.76, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034177', 'name': 'FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W', 'quantity': 1, 'net_total': 257.29, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00051119', 'name': 'ASTRA 4 VENTED SKIRT (5-DR) RH', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00027014', 'name': 'SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}]

In [229]:
#create loop to go through the pages
all_total_content = []

for page in range(1, num_pages + 1):
    table3 = read_pdf(input_file,
                    pages=page,
                    silent=True,
                    guess=False,
                    area=(700,320,820,575),
                    columns=[460,575],
                    pandas_options={'header': None},
                    encoding='windows-1254')
    
    if table3 != []:
        total_contenti=table3[0]
        all_total_content.append(total_contenti)

total_content = pd.concat(all_total_content).reset_index(drop=True)
display(total_content)

               0          1
0     Net Amount  £3,652.52
1       Carriage      £0.00
2      Total Net  £3,652.52
3     VAT Amount    £730.46
4  Invoice Total  £4,382.98

In [230]:
row_index = total_content.index[total_content[0] == "Invoice Total"].tolist()[0]

final_total = float(str(total_content[1][row_index]).replace('£','').replace(',',''))
display(final_total)

row_shipping = total_content.index[total_content[0] == "Carriage"].tolist()[0]
shipping = float(str(total_content[1][row_shipping]).replace('£','').replace(',',''))
display(shipping)

4382.98

0.0

In [231]:
#Adding shipping to the line_items
if shipping != 0:
    line_shipping = {"line_type":"shipping_expense",
                "sku": None,
                "name": "shipping",
                "Quantity": int(1),
                "net_total": float(shipping),
                "tax_type": "INPUT2"}

    line_items.append(line_shipping)
print(line_items)

[{'line_type': 'inventory', 'sku': 'R00049084', 'name': 'BMW Z3 FRONT LIP SPOILER', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088028', 'name': 'VW GOLF MK7 REAR DIFFUSER GLASS BLACK', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025025', 'name': 'MB W202 C CLASS 93-97 REAR LOWER APRON', 'quantity': 1, 'net_total': 96.66, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025070', 'name': 'MERCEDES W202 RIEGER FRONT BUMPER', 'quantity': 1, 'net_total': 223.94, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00053467', 'name': 'BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00051002', 'name': 'ASTRA F RADIATOR GRILLE', 'quantity': 1, 'net_total': 53.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055103', 'name': 'AUDI TT 8N SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 67.39, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055104', 'name': 'AUDI TT 8N SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 67.39, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025020', 'name': 'MB W202 C CLASS RERA WINDOW SPOILER', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025045', 'name': 'MB W201 190 SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025046', 'name': 'MB W201 190 SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025073', 'name': 'MB W202 C CLASS SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00025074', 'name': 'MW W202 C CLASS SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00048221', 'name': 'VW LUPO/SEAT AROSA SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 43.56, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055072', 'name': 'AUDI A4 B5 RS4 LOOK FRONT BUMPER', 'quantity': 1, 'net_total': 202.84, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055113', 'name': 'AUDI TT 8N VENTED SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055114', 'name': 'AUDI TT 8N VENTED SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 91.21, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055488', 'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER LEFT', 'quantity': 1, 'net_total': 57.18, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00055489', 'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT', 'quantity': 1, 'net_total': 57.18, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00057004', 'name': 'PORSCHE BOXSTER 986 SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 132.05, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00057005', 'name': 'PORSCHE BOXSTER 986 SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 132.05, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059012', 'name': 'VW GOLD MK4 FRONT GRILLE', 'quantity': 1, 'net_total': 40.16, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059017', 'name': 'VW GOLF MK4 FRONT BUMPER', 'quantity': 1, 'net_total': 202.84, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088247', 'name': 'AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER', 'quantity': 1, 'net_total': 111.63, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00099844', 'name': 'AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00099858', 'name': 'BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU', 'quantity': 1, 'net_total': 167.45, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088172', 'name': 'AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC', 'quantity': 1, 'net_total': 134.77, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059524', 'name': 'VW GOLF 6 GTi REAR DIFFUSER', 'quantity': 1, 'net_total': 101.42, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00059328', 'name': 'VW GOLF MK5 REAR LOWER APRON', 'quantity': 1, 'net_total': 104.82, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034134', 'name': 'FOCUS MK2 3 DOOR SIDE SKIRT LEFT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034135', 'name': 'FOCUS MK2 3 DOOR SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00088095', 'name': 'SKODA RAPID NH REAR DIFFUSER GLOSS BLACK', 'quantity': 1, 'net_total': 125.24, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00047006', 'name': 'POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT', 'quantity': 1, 'net_total': 36.76, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00047007', 'name': 'POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT', 'quantity': 1, 'net_total': 36.76, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00034177', 'name': 'FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W', 'quantity': 1, 'net_total': 257.29, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00051119', 'name': 'ASTRA 4 VENTED SKIRT (5-DR) RH', 'quantity': 1, 'net_total': 46.97, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'R00027014', 'name': 'SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT', 'quantity': 1, 'net_total': 66.71, 'tax_type': 'INPUT2'}]

In [232]:
payload = {}
keys = ["Source File",
        "Type",
        "Name",
        "Date",
        "Reference No.",
        "Order No.",
        "Transfer No.",
        "Document No.",
        "Line Items",
        "Total"]

values = [file_name,
        invoice_type,
        name,
        date,
        docnum,
        ordernum,
        transfernum,
        None,
        line_items,
        final_total]

for i, key in enumerate(keys):
    payload[key] = values[i]

payload

{'Source File': 'C:\\Users\\admin\\Downloads\\20.11.2023 £1,796.40 On-Line Auto Sport.pdf',
 'Type': 'Products',
 'Name': 'On-Line Auto Sport',
 'Date': '2024-03-11 00:00:00',
 'Reference No.': '212510',
 'Order No.': 'PO33922/PO34413',
 'Transfer No.': None,
 'Document No.': None,
 'Line Items': [{'line_type': 'inventory',
   'sku': 'R00049084',
   'name': 'BMW Z3 FRONT LIP SPOILER',
   'quantity': 1,
   'net_total': 91.21,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00088028',
   'name': 'VW GOLF MK7 REAR DIFFUSER GLASS BLACK',
   'quantity': 1,
   'net_total': 134.77,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025025',
   'name': 'MB W202 C CLASS 93-97 REAR LOWER APRON',
   'quantity': 1,
   'net_total': 96.66,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025070',
   'name': 'MERCEDES W202 RIEGER FRONT BUMPER',
   'quantity': 1,
   'net_total': 223.94,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00053467',
   'name': 'BMW 3 SERIES F30/F31 REAR DIFFUSER 335/340',
   'quantity': 1,
   'net_total': 134.77,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00051002',
   'name': 'ASTRA F RADIATOR GRILLE',
   'quantity': 1,
   'net_total': 53.77,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055103',
   'name': 'AUDI TT 8N SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 67.39,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055104',
   'name': 'AUDI TT 8N SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 67.39,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025020',
   'name': 'MB W202 C CLASS RERA WINDOW SPOILER',
   'quantity': 1,
   'net_total': 46.97,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025045',
   'name': 'MB W201 190 SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 46.97,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025046',
   'name': 'MB W201 190 SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 46.97,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025073',
   'name': 'MB W202 C CLASS SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 66.71,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00025074',
   'name': 'MW W202 C CLASS SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 66.71,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00048221',
   'name': 'VW LUPO/SEAT AROSA SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 43.56,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055072',
   'name': 'AUDI A4 B5 RS4 LOOK FRONT BUMPER',
   'quantity': 1,
   'net_total': 202.84,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055113',
   'name': 'AUDI TT 8N VENTED SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 91.21,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055114',
   'name': 'AUDI TT 8N VENTED SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 91.21,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055488',
   'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER LEFT',
   'quantity': 1,
   'net_total': 57.18,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00055489',
   'name': 'AUDI A5/S5 SIDE SKIRT SPLITTER RIGHT',
   'quantity': 1,
   'net_total': 57.18,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00057004',
   'name': 'PORSCHE BOXSTER 986 SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 132.05,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00057005',
   'name': 'PORSCHE BOXSTER 986 SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 132.05,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00059012',
   'name': 'VW GOLD MK4 FRONT GRILLE',
   'quantity': 1,
   'net_total': 40.16,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00059017',
   'name': 'VW GOLF MK4 FRONT BUMPER',
   'quantity': 1,
   'net_total': 202.84,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00088247',
   'name': 'AUDI A3 8P 5 DOOR FACELIFT REAR DIFFUSER',
   'quantity': 1,
   'net_total': 111.63,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00099844',
   'name': 'AUDI A4 B8/B81 07-11 REAR DIFFUSER C-F LOOK',
   'quantity': 1,
   'net_total': 134.77,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00099858',
   'name': 'BMW E85 Z4 06-09 REAR LOWER APRON C-F LOOK QU',
   'quantity': 1,
   'net_total': 167.45,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00088172',
   'name': 'AUDI S3 8V 12-16 HATCH REAR DIFFUSER GLOSS BLAC',
   'quantity': 1,
   'net_total': 134.77,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00059524',
   'name': 'VW GOLF 6 GTi REAR DIFFUSER',
   'quantity': 1,
   'net_total': 101.42,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00059328',
   'name': 'VW GOLF MK5 REAR LOWER APRON',
   'quantity': 1,
   'net_total': 104.82,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00034134',
   'name': 'FOCUS MK2 3 DOOR SIDE SKIRT LEFT',
   'quantity': 1,
   'net_total': 66.71,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00034135',
   'name': 'FOCUS MK2 3 DOOR SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 66.71,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00088095',
   'name': 'SKODA RAPID NH REAR DIFFUSER GLOSS BLACK',
   'quantity': 1,
   'net_total': 125.24,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00047006',
   'name': 'POLO MK2/3 CPIPE SIDE SKIRT LEFT NO CUT-OUT',
   'quantity': 1,
   'net_total': 36.76,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00047007',
   'name': 'POLO MK2/3 CPIPE SIDE SKIRT RIGHT NO CUT-OUT',
   'quantity': 1,
   'net_total': 36.76,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00034177',
   'name': 'FORD FOCUS MK2 FACELIFT RE STYLE BUMPER NO W',
   'quantity': 1,
   'net_total': 257.29,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00051119',
   'name': 'ASTRA 4 VENTED SKIRT (5-DR) RH',
   'quantity': 1,
   'net_total': 46.97,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'R00027014',
   'name': 'SEAT LEON 5F 3 DOOR SIDE SKIRT RIGHT',
   'quantity': 1,
   'net_total': 66.71,
   'tax_type': 'INPUT2'}],
 'Total': 4382.98}