In [17]:
import os
import PyPDF2
import numpy as np
import pandas as pd
from tabula.io import read_pdf
from datetime import datetime
import re

In [18]:
file_name = r"C:\Users\admin\Documents\Toolbank\16.04.2024 £768.50 Toolbank.pdf"
r"C:\Users\admin\Documents\Toolbank\16.04.2024 £768.50 Toolbank.pdf"

'C:\\Users\\admin\\Documents\\Toolbank\\16.04.2024 £768.50 Toolbank.pdf'

In [19]:
invoice_type = "Products"
# inputFolder = os.path.abspath('..\\Forge')

input_file = fr"C:\Users\admin\Downloads\16.04.2024 £768.50 Toolbank.pdf"

In [20]:
table1 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(19,384,62.6,572),
                  columns=[484,572],
                  pandas_options={'header': None},
                  encoding="windows-1254")

heading = table1[0]
print(heading)

name = "ToolBank"
docnum = heading[1][0]
print(docnum)

date = heading[1][1]
#print(date)
date = str(datetime.strptime(date, "%d/%m/%Y"))
print(date)

                0           1
0  Invoice Number    09177324
1  Tax Point Date  16/04/2024
2  Account Number  1 700329 0
09177324
2024-04-16 00:00:00

In [21]:
table2 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(232,25,242,144),
                  columns=[77,144],
                  pandas_options={'header': None},
                  encoding="windows-1254")

info = table2[0]
#print(info)

ordernum = info[1][0]
print(ordernum)

transfernum = None
print(transfernum)

PO35465
None

In [22]:
table3 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=(282,20,650,567),
                  columns=[77,97,283,314,343,367,392,417,453,545,557,566],
                  pandas_options={'header': None},
                  encoding="windows-1254")
content=table3[0]


#print(h)

num_rows = len(content)
print(num_rows)

# Choose the appropriate area and columns based on the number of rows
area = (282,20,790,567)
columns = [77,97,283,314,343,367,392,417,453,545,557,566]

# if num_rows >= 16 :  
#     area = (282,20,650,567)
#     columns = [77,97,283,314,343,367,392,417,453,545,557,566]
# else:
#     area = (282,20,496,567)
#     columns = [77,97,283,314,343,367,392,417,453,545,557,566]

table3 = read_pdf(input_file,
                  pages="1",
                  silent=True,
                  guess=False,
                  area=area,
                  columns=columns,
                  pandas_options={'header': None},
                  encoding='windows-1254')

content = table3[0]

content

16

,0,1,2,3,4,5,6,7,8,9,10,11
0,RST670,6 *,RSTHARDWOOD METRE STICK PLAIN,£5.65,EA,NaN,NaN,NaN,£2.49,£14.94,S,N
1,ROU55010,1,R/NECK PRO LEAD WORKING TOOL SET (4PC),£66.64,EA,40.00,10.00,NaN,NaN,£35.99,S,Y
2,ROU55008,1,R/NECK PRO LEAD SETTING IN STICK,£16.66,EA,40.00,10.00,NaN,NaN,£9.00,S,Y
3,RID57018,1 *,RIDGID C15/22 C-STYLE COPPER CUTTER,£35.77,EA,25.00,NaN,NaN,NaN,£26.83,S,N
4,Q/G1988933,4,Q/GRIPOHBC ACCESSORY WIDE PADS,£8.01,EA,33.33,10.00,NaN,NaN,£19.22,S,Y
5,HULSK,11 *,HULTAFOR SK SAFETY KNIFE,£5.46,EA,33.33,10.00,NaN,NaN,£36.04,S,Y
6,FSK1001621,3,FISKARS 1001621 BOWSAW 21IN,£15.00,EA,30.00,10.00,NaN,NaN,£28.35,S,Y
7,FAILD,1 *,FAI/FULL LEAD DRESSER,£23.53,EA,40.00,10.00,NaN,NaN,£12.71,S,Y
8,CRVC301242,2 *,CARVER MULTICLAMP 3 IN 1 CLAMP WITH CARRY CASE,£347.82,EA,33.33,10.00,NaN,NaN,£417.40,S,Y
9,BAI1470,1 *,BAILEY 1470 UNI 3/4IN DRAIN ROD SET 2 TOOLS,£66.56,EA,33.33,10.00,NaN,NaN,£39.94,S,Y
10,NaN,NaN,Payment is due 14,days from th,e invoice d,ate,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,Cd,Rate,Taxable,Tax,R,ebateable,Non Reb,ateable Total Goods,NaN,NaN
12,Items marked with,* are,from a quality assured source S,20.00,£640.42,128.08,NaN,598.65,NaN,41.77 £640.42,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total VAT £128.08,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amoun,t Payable £768.50,NaN,NaN
15,NaN,RE,"MEMBER WE ONLY SERVE YOU, NOT YOUR CUSTOMERS ====",======,======,=====,=====,=====,=======,========,NaN,NaN

In [23]:

#To remove "*" and "£"
content[[3,8,9]] = content[[3,8,9]].replace('[£, ]','', regex=True).astype('string')
content[[1]] = content[[1]].replace('[*, ]','', regex=True).astype('string')
content

#print(content)
content = content[content[1].notnull()].iloc[:, 0:].reset_index(drop=True)  # Remove NaN
content = content.dropna(subset=[1,10])  # Remove rows with NaN in column 1,10
content[1] = pd.to_numeric(content[1], errors='coerce')  # Remove anything that not number in column 1

content

,0,1,2,3,4,5,6,7,8,9,10,11
0,RST670,6,RSTHARDWOOD METRE STICK PLAIN,5.65,EA,NaN,NaN,NaN,2.49,14.94,S,N
1,ROU55010,1,R/NECK PRO LEAD WORKING TOOL SET (4PC),66.64,EA,40.00,10.00,NaN,<NA>,35.99,S,Y
2,ROU55008,1,R/NECK PRO LEAD SETTING IN STICK,16.66,EA,40.00,10.00,NaN,<NA>,9.00,S,Y
3,RID57018,1,RIDGID C15/22 C-STYLE COPPER CUTTER,35.77,EA,25.00,NaN,NaN,<NA>,26.83,S,N
4,Q/G1988933,4,Q/GRIPOHBC ACCESSORY WIDE PADS,8.01,EA,33.33,10.00,NaN,<NA>,19.22,S,Y
5,HULSK,11,HULTAFOR SK SAFETY KNIFE,5.46,EA,33.33,10.00,NaN,<NA>,36.04,S,Y
6,FSK1001621,3,FISKARS 1001621 BOWSAW 21IN,15.00,EA,30.00,10.00,NaN,<NA>,28.35,S,Y
7,FAILD,1,FAI/FULL LEAD DRESSER,23.53,EA,40.00,10.00,NaN,<NA>,12.71,S,Y
8,CRVC301242,2,CARVER MULTICLAMP 3 IN 1 CLAMP WITH CARRY CASE,347.82,EA,33.33,10.00,NaN,<NA>,417.40,S,Y
9,BAI1470,1,BAILEY 1470 UNI 3/4IN DRAIN ROD SET 2 TOOLS,66.56,EA,33.33,10.00,NaN,<NA>,39.94,S,Y

In [24]:
content.rename(columns={
    0: 'Stock Number',
    1: 'Qty',
    2: 'Description',
    3: 'List Price',
    4: 'Per',
    5: 'Disc 1',
    6: 'Disc 2',
    7: 'Disc 3',
    8: 'Net Price',
    9: 'Value',
    10: "Tax Code ",
    11: "Boolean"}, inplace=True)

display(content)

,Stock Number,Qty,Description,List Price,Per,Disc 1,Disc 2,Disc 3,Net Price,Value,Tax Code,Boolean
0,RST670,6,RSTHARDWOOD METRE STICK PLAIN,5.65,EA,NaN,NaN,NaN,2.49,14.94,S,N
1,ROU55010,1,R/NECK PRO LEAD WORKING TOOL SET (4PC),66.64,EA,40.00,10.00,NaN,<NA>,35.99,S,Y
2,ROU55008,1,R/NECK PRO LEAD SETTING IN STICK,16.66,EA,40.00,10.00,NaN,<NA>,9.00,S,Y
3,RID57018,1,RIDGID C15/22 C-STYLE COPPER CUTTER,35.77,EA,25.00,NaN,NaN,<NA>,26.83,S,N
4,Q/G1988933,4,Q/GRIPOHBC ACCESSORY WIDE PADS,8.01,EA,33.33,10.00,NaN,<NA>,19.22,S,Y
5,HULSK,11,HULTAFOR SK SAFETY KNIFE,5.46,EA,33.33,10.00,NaN,<NA>,36.04,S,Y
6,FSK1001621,3,FISKARS 1001621 BOWSAW 21IN,15.00,EA,30.00,10.00,NaN,<NA>,28.35,S,Y
7,FAILD,1,FAI/FULL LEAD DRESSER,23.53,EA,40.00,10.00,NaN,<NA>,12.71,S,Y
8,CRVC301242,2,CARVER MULTICLAMP 3 IN 1 CLAMP WITH CARRY CASE,347.82,EA,33.33,10.00,NaN,<NA>,417.40,S,Y
9,BAI1470,1,BAILEY 1470 UNI 3/4IN DRAIN ROD SET 2 TOOLS,66.56,EA,33.33,10.00,NaN,<NA>,39.94,S,Y

In [25]:
dict_content = content.to_dict(orient='records')
dict_content


line_items=[]
for item in dict_content:
    # print(item)
    
    partNum = item['Stock Number']
    desc = item['Description']
    quantity = item['Qty']
    netTotal = item['Value']

    print(partNum)
    
    line_item = {"line_type": "inventory",
                        "sku": partNum,
                        "name": desc,
                        "quantity": int(quantity),
                        "net_total": float(netTotal),
                        "tax_type": "INPUT2"}
    
    line_items.append(line_item)
    
print(line_items)

RST670
ROU55010
ROU55008
RID57018
Q/G1988933
HULSK
FSK1001621
FAILD
CRVC301242
BAI1470
[{'line_type': 'inventory', 'sku': 'RST670', 'name': 'RSTHARDWOOD METRE STICK PLAIN', 'quantity': 6, 'net_total': 14.94, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'ROU55010', 'name': 'R/NECK  PRO LEAD WORKING TOOL SET (4PC)', 'quantity': 1, 'net_total': 35.99, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'ROU55008', 'name': 'R/NECK  PRO LEAD SETTING IN STICK', 'quantity': 1, 'net_total': 9.0, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'RID57018', 'name': 'RIDGID  C15/22 C-STYLE COPPER CUTTER', 'quantity': 1, 'net_total': 26.83, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'Q/G1988933', 'name': 'Q/GRIPOHBC ACCESSORY WIDE PADS', 'quantity': 4, 'net_total': 19.22, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'HULSK', 'name': 'HULTAFOR SK SAFETY KNIFE', 'quantity': 11, 'net_total': 36.04, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'FSK1001621', 'name': 'FISKARS 1001621 BOWSAW 21IN', 'quantity': 3, 'net_total': 28.35, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'FAILD', 'name': 'FAI/FULL LEAD DRESSER', 'quantity': 1, 'net_total': 12.71, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'CRVC301242', 'name': 'CARVER  MULTICLAMP 3 IN 1 CLAMP WITH CARRY CASE', 'quantity': 2, 'net_total': 417.4, 'tax_type': 'INPUT2'}, {'line_type': 'inventory', 'sku': 'BAI1470', 'name': 'BAILEY  1470 UNI 3/4IN DRAIN ROD SET 2 TOOLS', 'quantity': 1, 'net_total': 39.94, 'tax_type': 'INPUT2'}]

In [26]:
for line in line_items:
    try:
        print(line['net_total'])
        total = "hello" + 2
        print(total)

    except:
        print('there is an error')

14.94
there is an error
35.99
there is an error
9.0
there is an error
26.83
there is an error
19.22
there is an error
36.04
there is an error
28.35
there is an error
12.71
there is an error
417.4
there is an error
39.94
there is an error

In [27]:
table4 = read_pdf(input_file,
            pages="1",
            silent=True,
            guess=False,
            area=(355,410,780,550),
            columns=[500,550],
            pandas_options={'header': None},
            encoding='windows-1254')

total_content=table4[0]

#To remove "£"
total_content[[1]] = total_content[[1]].replace('[£, ]','', regex=True).astype('string')
#print(total_content)

total_content = total_content.dropna(subset=[0,1])  # Remove rows with NaN in column 0
total_content = total_content.dropna(subset=[0]).reset_index(drop=True)
total_content

                   0           1
0  le Non Rebateable  TotalGoods
1           65 41.77      640.42
2          Total VAT      128.08
3     Amount Payable      768.50

In [28]:
row_index = total_content.index[total_content[0] == "Amount Payable"].tolist()[0]


final_total = str(total_content[1][row_index])
final_total = float(final_total.replace(","," "))
final_total

768.5

In [29]:
## merge invoice heading and line items information..
## ..into one dict variable, 'payload'
payload = {}
keys = ["Source File",
        "Type",
        "Name",
        "Date",
        "Reference No.",
        "Order No.",
        "Transfer No.",
        "Document No.",
        "Line Items",
        "Total"]

values = [file_name,
        invoice_type,
        name,
        date,
        docnum,
        ordernum,
        transfernum,
        docnum,
        line_items,
        final_total]

for i, key in enumerate(keys):
    payload[key] = values[i]

payload

{'Source File': 'C:\\Users\\admin\\Documents\\Toolbank\\16.04.2024 £768.50 Toolbank.pdf',
 'Type': 'Products',
 'Name': 'ToolBank',
 'Date': '2024-04-16 00:00:00',
 'Reference No.': '09177324',
 'Order No.': 'PO35465',
 'Transfer No.': None,
 'Document No.': '09177324',
 'Line Items': [{'line_type': 'inventory',
   'sku': 'RST670',
   'name': 'RSTHARDWOOD METRE STICK PLAIN',
   'quantity': 6,
   'net_total': 14.94,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'ROU55010',
   'name': 'R/NECK  PRO LEAD WORKING TOOL SET (4PC)',
   'quantity': 1,
   'net_total': 35.99,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'ROU55008',
   'name': 'R/NECK  PRO LEAD SETTING IN STICK',
   'quantity': 1,
   'net_total': 9.0,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'RID57018',
   'name': 'RIDGID  C15/22 C-STYLE COPPER CUTTER',
   'quantity': 1,
   'net_total': 26.83,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'Q/G1988933',
   'name': 'Q/GRIPOHBC ACCESSORY WIDE PADS',
   'quantity': 4,
   'net_total': 19.22,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'HULSK',
   'name': 'HULTAFOR SK SAFETY KNIFE',
   'quantity': 11,
   'net_total': 36.04,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'FSK1001621',
   'name': 'FISKARS 1001621 BOWSAW 21IN',
   'quantity': 3,
   'net_total': 28.35,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'FAILD',
   'name': 'FAI/FULL LEAD DRESSER',
   'quantity': 1,
   'net_total': 12.71,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'CRVC301242',
   'name': 'CARVER  MULTICLAMP 3 IN 1 CLAMP WITH CARRY CASE',
   'quantity': 2,
   'net_total': 417.4,
   'tax_type': 'INPUT2'},
  {'line_type': 'inventory',
   'sku': 'BAI1470',
   'name': 'BAILEY  1470 UNI 3/4IN DRAIN ROD SET 2 TOOLS',
   'quantity': 1,
   'net_total': 39.94,
   'tax_type': 'INPUT2'}],
 'Total': 768.5}

In [30]:
shopify_sku = "RST-RST670"
supplier_sku = "RST670"

if shopify_sku == supplier_sku:
    print("correct sku")
else:
    print("missing")

missing